import "../register-secrets.js";
import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";
import { getOrgContext } from "@agent-native/core/org";
// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers (Nitro on Netlify,
// Vercel, AWS-Lambda) include every action module in the server bundle —
// a runtime filesystem scan finds nothing in a bundled function, which is
// why `autoDiscoverActions` on its own produces 404s for action routes in
// production.
import actionsRegistry from "../../.generated/actions-registry.js";

export default createAgentChatPlugin({
  appId: "clips",
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  resolveOrgId: async (event) => (await getOrgContext(event)).orgId,
});
