import "../register-secrets.js";
import {
  createAgentChatPlugin,
  loadActionsFromStaticRegistry,
} from "@agent-native/core/server";
import { getOrgContext } from "@agent-native/core/org";
// Static-import registry generated by @agent-native/core's Vite plugin at
// build time. Using a static import ensures bundlers (Nitro on Netlify,
// Vercel, AWS-Lambda) include every action module in the server bundle —
// a runtime filesystem scan finds nothing in a bundled function, which is
// why `autoDiscoverActions` on its own produces 404s for action routes in
// production.
import actionsRegistry from "../../.generated/actions-registry.js";

const INITIAL_TOOL_NAMES = [
  "view-screen",
  "list-recordings",
  "search-recordings",
  "get-recording-player-data",
  "create-recording",
  "import-loom-recording",
  "update-recording",
  "finalize-recording",
  "cleanup-transcript",
  "regenerate-summary",
  "regenerate-title",
  "regenerate-chapters",
  "trim-recording",
  "remove-silences",
  "remove-filler-words",
  "export-to-brain",
  "navigate",
  "refresh-list",
];

export default createAgentChatPlugin({
  appId: "clips",
  actions: loadActionsFromStaticRegistry(actionsRegistry),
  initialToolNames: INITIAL_TOOL_NAMES,
  resolveOrgId: async (event) => (await getOrgContext(event)).orgId,
});
